"""Pydantic request and response schemas."""

from app.schemas.api import (
    CompileRequest,
    CompileResponse,
    HealthResponse,
    KnowledgeReference,
    KnowledgeRetrievalTelemetry,
    RootResponse,
)
from app.schemas.interview import (
    InterviewAnswer,
    InterviewAnswerRequest,
    InterviewQuestion,
    InterviewSessionResponse,
    InterviewStartRequest,
)
from app.schemas.project import (
    MemoryCategory,
    MemorySource,
    MemoryStatus,
    Project,
    ProjectContext,
    ProjectCreate,
    ProjectMemory,
    ProjectMemoryCreate,
    ProjectMemoryUpdate,
    ProjectUpdate,
)

from app.schemas.candidate_memory import (
    CandidateApprovalRequest,
    CandidateApprovalResponse,
    CandidateMemory,
    CandidateMemoryCreate,
    CandidateMemoryUpdate,
    CandidateRejectionRequest,
    CandidateStatus,
    ExtractCandidatesRequest,
)

from app.schemas.agent_preset import (
    AgentPreset,
    AgentTarget,
    SUPPORTED_AGENTS,
)

from app.schemas.knowledge import (
    BatchDocumentIngestionResponse,
    DocumentIngestionResult,
    IngestDirectoryRequest,
    IngestFileRequest,
    IngestionStatus,
    KnowledgeChunk,
    KnowledgeContextItem,
    KnowledgeIndexRequest,
    KnowledgeIndexResponse,
    KnowledgeSearchRequest,
    KnowledgeSearchResponse,
    KnowledgeSearchResult,
    KnowledgeSource,
    KnowledgeSourceResponse,
    SourceType,
    SUPPORTED_SOURCE_TYPES,
)

__all__ = [
    "CompileRequest",
    "CompileResponse",
    "HealthResponse",
    "KnowledgeReference",
    "KnowledgeRetrievalTelemetry",
    "RootResponse",
    "InterviewAnswer",
    "InterviewAnswerRequest",
    "InterviewQuestion",
    "InterviewSessionResponse",
    "InterviewStartRequest",
    "MemoryCategory",
    "MemorySource",
    "MemoryStatus",
    "Project",
    "ProjectContext",
    "ProjectCreate",
    "ProjectMemory",
    "ProjectMemoryCreate",
    "ProjectMemoryUpdate",
    "ProjectUpdate",
    "CandidateApprovalRequest",
    "CandidateApprovalResponse",
    "CandidateMemory",
    "CandidateMemoryCreate",
    "CandidateMemoryUpdate",
    "CandidateRejectionRequest",
    "CandidateStatus",
    "ExtractCandidatesRequest",
    "AgentPreset",
    "AgentTarget",
    "SUPPORTED_AGENTS",
    "BatchDocumentIngestionResponse",
    "DocumentIngestionResult",
    "IngestDirectoryRequest",
    "IngestFileRequest",
    "IngestionStatus",
    "KnowledgeChunk",
    "KnowledgeContextItem",
    "KnowledgeIndexRequest",
    "KnowledgeIndexResponse",
    "KnowledgeSearchRequest",
    "KnowledgeSearchResponse",
    "KnowledgeSearchResult",
    "KnowledgeSource",
    "KnowledgeSourceResponse",
    "SourceType",
    "SUPPORTED_SOURCE_TYPES",
]


