"""Prompt Refiner and Automated Refinement Loop for Prompt Compiler."""

import asyncio
import concurrent.futures
from typing import Any
from pydantic import BaseModel, Field

from app.config import settings
from app.engine.critic import PromptCritic, ValidationResult
from app.engine.generator import PromptGenerationResult, PromptGenerator
from app.engine.requirements import RequirementAnalysis
from app.schemas.knowledge import KnowledgeContextItem
from app.schemas.project import ProjectContext



class RefinementIterationRecord(BaseModel):
    """Record of a single iteration within the refinement loop."""

    attempt: int = Field(..., description="Iteration attempt number (0 for initial draft).")
    prompt_snippet: str = Field(..., description="First 200 characters of the prompt draft.")
    overall_valid: bool = Field(..., description="Whether the prompt was deemed valid in this iteration.")
    error_count: int = Field(..., description="Number of error-severity issues found.")
    warning_count: int = Field(..., description="Number of warning-severity issues found.")
    issue_categories: list[str] = Field(default_factory=list, description="Categories of issues identified.")


class RefinementResult(BaseModel):
    """Result produced by the PromptRefiner orchestration."""

    final_prompt: str = Field(..., description="The final compiled prompt after refinement.")
    validation_result: ValidationResult = Field(..., description="The final validation result.")
    refinement_attempts: int = Field(
        default=0,
        description="Number of automated refinement attempts performed (0 if initially valid).",
    )
    task_type: str = Field(..., description="The canonical task type.")
    template_name: str = Field(..., description="Name of the prompt template used.")
    converged: bool = Field(
        ...,
        description="Whether the prompt successfully converged to overall_valid=True.",
    )
    history: list[RefinementIterationRecord] = Field(
        default_factory=list,
        description="Detailed trace of iterations and validation states.",
    )


class PromptRefiner:
    """Automated prompt refinement loop engine that iteratively validates and improves prompts.

    Flow:
    1. Evaluates an initial prompt generation with PromptCritic.
    2. If valid (overall_valid=True), terminates immediately without invoking additional LLM calls.
    3. If invalid with actionable issues, passes validation findings to PromptGenerator for targeted refinement.
    4. Re-validates the refined prompt draft with PromptCritic.
    5. Repeats until validation succeeds or max_iterations is reached.
    """

    ACTIONABLE_CATEGORIES: frozenset[str] = frozenset(
        {
            "requirement_missing",
            "constraint_missing",
            "invented_requirement",
            "missing_information_lost",
            "structural_problem",
            "task_type_mismatch",
            "ambiguity",
            "quality_problem",
        }
    )

    def __init__(
        self,
        prompt_generator: PromptGenerator,
        prompt_critic: PromptCritic,
        max_iterations: int | None = None,
    ) -> None:
        """Initialize PromptRefiner.

        Args:
            prompt_generator: Configured PromptGenerator instance.
            prompt_critic: Configured PromptCritic instance.
            max_iterations: Maximum allowed refinement attempts (defaults to settings.MAX_REFINEMENT_ITERATIONS).
        """
        self.prompt_generator = prompt_generator
        self.prompt_critic = prompt_critic
        self.max_iterations = (
            max_iterations
            if max_iterations is not None
            else settings.max_refinement_iterations
        )

    def is_actionable(self, validation_result: ValidationResult) -> bool:
        """Determine whether the validation result contains actionable issues that can be fixed by refinement."""
        if validation_result.overall_valid:
            return False
        return any(
            issue.category in self.ACTIONABLE_CATEGORIES
            for issue in validation_result.issues
        )

    async def run_loop_async(
        self,
        analysis: RequirementAnalysis,
        initial_generation: PromptGenerationResult,
        use_llm_critic: bool = False,
        project_context: ProjectContext | None = None,
        retrieved_knowledge: list[KnowledgeContextItem] | None = None,
    ) -> RefinementResult:
        """Asynchronously run the automated prompt refinement loop.

        Args:
            analysis: Validated RequirementAnalysis instance.
            initial_generation: The initial draft generated by PromptGenerator.
            use_llm_critic: Whether to invoke the LLM semantic critic in addition to deterministic rules.
            project_context: Optional persistent ProjectContext instance.
            retrieved_knowledge: Optional list of retrieved knowledge context items.

        Returns:
            RefinementResult containing the final prompt, validation result, and iteration metrics.
        """
        current_prompt = initial_generation.final_prompt
        template_name = initial_generation.template_name
        task_type = initial_generation.task_type
        history: list[RefinementIterationRecord] = []

        # Step 1: Initial quality and fidelity validation
        critic_kwargs: dict[str, Any] = {"use_llm": use_llm_critic}
        if project_context is not None:
            critic_kwargs["project_context"] = project_context
        if retrieved_knowledge is not None:
            critic_kwargs["retrieved_knowledge"] = retrieved_knowledge

        validation_result = await self.prompt_critic.validate_async(
            analysis,
            current_prompt,
            **critic_kwargs,
        )

        history.append(
            RefinementIterationRecord(
                attempt=0,
                prompt_snippet=current_prompt[:200] if isinstance(current_prompt, str) else str(current_prompt)[:200],
                overall_valid=validation_result.overall_valid,
                error_count=len(validation_result.errors),
                warning_count=len(validation_result.warnings),
                issue_categories=[issue.category for issue in validation_result.issues],
            )
        )

        # Step 2: Immediate exit if initial generation is already valid
        if validation_result.overall_valid:
            return RefinementResult(
                final_prompt=current_prompt,
                validation_result=validation_result,
                refinement_attempts=0,
                task_type=task_type,
                template_name=template_name,
                converged=True,
                history=history,
            )

        # Step 3: Iterative refinement loop
        attempts = 0
        while attempts < self.max_iterations:
            # Check if remaining issues are actionable
            if not self.is_actionable(validation_result):
                break

            attempts += 1

            # Generate refined prompt addressing critic findings
            gen_kwargs: dict[str, Any] = {
                "previous_prompt": current_prompt,
                "validation_result": validation_result,
            }
            if project_context is not None:
                gen_kwargs["project_context"] = project_context
            if retrieved_knowledge is not None:
                gen_kwargs["retrieved_knowledge"] = retrieved_knowledge

            refined_generation = await self.prompt_generator.generate_async(
                analysis,
                **gen_kwargs,
            )
            if hasattr(refined_generation, "final_prompt") and isinstance(refined_generation.final_prompt, str):
                current_prompt = refined_generation.final_prompt
            else:
                current_prompt = str(getattr(refined_generation, "final_prompt", refined_generation))

            # Re-evaluate refined prompt
            critic_kwargs_loop: dict[str, Any] = {"use_llm": use_llm_critic}
            if project_context is not None:
                critic_kwargs_loop["project_context"] = project_context
            if retrieved_knowledge is not None:
                critic_kwargs_loop["retrieved_knowledge"] = retrieved_knowledge

            validation_result = await self.prompt_critic.validate_async(
                analysis,
                current_prompt,
                **critic_kwargs_loop,
            )

            history.append(
                RefinementIterationRecord(
                    attempt=attempts,
                    prompt_snippet=current_prompt[:200],
                    overall_valid=validation_result.overall_valid,
                    error_count=len(validation_result.errors),
                    warning_count=len(validation_result.warnings),
                    issue_categories=[issue.category for issue in validation_result.issues],
                )
            )

            # If validation succeeds, terminate early
            if validation_result.overall_valid:
                return RefinementResult(
                    final_prompt=current_prompt,
                    validation_result=validation_result,
                    refinement_attempts=attempts,
                    task_type=task_type,
                    template_name=template_name,
                    converged=True,
                    history=history,
                )

        # Max iterations reached or non-actionable; return latest state
        return RefinementResult(
            final_prompt=current_prompt,
            validation_result=validation_result,
            refinement_attempts=attempts,
            task_type=task_type,
            template_name=template_name,
            converged=validation_result.overall_valid,
            history=history,
        )

    def run_loop(
        self,
        analysis: RequirementAnalysis,
        initial_generation: PromptGenerationResult,
        use_llm_critic: bool = False,
        project_context: ProjectContext | None = None,
        retrieved_knowledge: list[KnowledgeContextItem] | None = None,
    ) -> RefinementResult:
        """Synchronously run the automated prompt refinement loop."""
        try:
            loop = asyncio.get_running_loop()
        except RuntimeError:
            loop = None

        if loop and loop.is_running():
            with concurrent.futures.ThreadPoolExecutor(max_workers=1) as executor:
                return executor.submit(
                    asyncio.run,
                    self.run_loop_async(
                        analysis,
                        initial_generation,
                        use_llm_critic,
                        project_context=project_context,
                        retrieved_knowledge=retrieved_knowledge,
                    ),
                ).result()
        else:
            return asyncio.run(
                self.run_loop_async(
                    analysis,
                    initial_generation,
                    use_llm_critic,
                    project_context=project_context,
                    retrieved_knowledge=retrieved_knowledge,
                )
            )

